version: "3.7"

services:
  db:
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-db:/var/lib/postgresql/data/

volumes:
  postgres-db:
    driver: local