FROM golang:1.19-alpine3.16 AS builder


WORKDIR /app

COPY go.mod ./
RUN go mod download
RUN go mod verify

COPY . .

WORKDIR /app/cmd/api

RUN go build -o main main.go


# Build tiny image
FROM alpine:latest

WORKDIR /app

COPY wait-for.sh .

COPY --from=builder /app/cmd/api/main /app


# Don't run as root
RUN adduser -D -u 1001 bogo
RUN chown -R bogo:bogo /app
USER bogo

EXPOSE 3000

CMD ["./main"]