version: "3.7"

services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data

  asynq-ui:
     image: hibiken/asynqmon
     ports:
      - '4000:8080'
     environment:
      REDIS_ADDR: redis:6379
      

  db:
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-db:/var/lib/postgresql/data/

  mailhog:
      image: mailhog/mailhog
      logging:
        driver: 'none'  # disable saving logs
      ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web ui

volumes:
  postgres-db:
    driver: local
  redis:
    driver: local