apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-deployment
  namespace: go-masterclass
spec:
  replicas: 1
  selector:
    matchLabels:
      module-name: workers-module
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        module-name: workers-module
    spec:
      containers:
      - image: ghcr.io/bogocvetkov/go_masterclass/workers:main
        name: workers-image
        # Testing with locally build images
        # imagePullPolicy: Never
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
        resources:
           limits:
              cpu: 200m
              memory: 150Mi
           requests:
              cpu: 100m
              memory: 100Mi
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: DB_URL
          - name: PORT
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: PORT
          - name: ENV
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: ENV
          - name: GRPC_PORT
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: GRPC_PORT
          - name: GRPC_GATEWAY_PORT
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: GRPC_GATEWAY_PORT
          - name: DB_DRIVER
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: DB_DRIVER
          - name: TOKEN_DURATION
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: TOKEN_DURATION
          - name: TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: TOKEN_SECRET
          - name: REFRESH_TOKEN_DURATION
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: REFRESH_TOKEN_DURATION
          - name: REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: REFRESH_TOKEN_SECRET
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: SMTP_HOST
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: SMTP_PORT
          - name: ENCRYTION
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: ENCRYTION
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: SMTP_USER
          - name: SMTP_PASS
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: SMTP_PASS
          - name: SMTP_FROM
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: SMTP_FROM
          - name: REDIS
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: REDIS
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: REDIS_USER
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                  name: app-secret
                  key: REDIS_PASS
      imagePullSecrets:
      - name: ghrc-auth