name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: api
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}"
          tags: "${{ github.sha }},${{ github.ref_name }}"

      - name: Log in GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx # recommended by Docker to optimize the build process
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: "${{ steps.metadata.outputs.tags }}"